name: Run branch config set

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_master_protection_config:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./scripts/*

      - name: Run master protection config
        env:
          TOKEN: ${{ secrets.ALL_REPOS_ACCESS_TOKEN }} # secrets.GITHUB_TOKEN is only available inside repo where aciton is running.
        run: |
          ./scripts/master_branch_protect.sh
          ./scripts/develop_branch_protect.sh
          ./scripts/delete_fature_branch.sh
