on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_master_protection_config:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run master protection config
        run: |
          ./scripts/master_branch_protect.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}