name: Tagging template

on:
  workflow_call:
    inputs:
      VERSION:
        description: "Application version"
        type: string
        required: true
        default: "1.0.0"

jobs:
  create_tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_latest_tag
        run: |
          # Fetch tags and sort them in descending order by version
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          LATEST_SEMVER_TAG=$(git tag -l | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          echo "latest_tag=$LATEST_SEMVER_TAG" >> $GITHUB_ENV

      - name: Version check
        run: |
          # Convert VERSION_1 and VERSION_2 to positional variables
          new_tag=${{ inputs.VERSION }}
          last_tag=${{ env.LATEST_SEMVER_TAG || '0.0.0' }}

          # Compare versions
          compare_versions() {
            if [[ $(echo -e "$new_tag\n$last_tag" | sort -V | head -n1) == "$last_tag" ]] && [[ "$new_tag" != "$last_tag" ]]; then
              echo "Last tag $last_tag is higher than New tag $new_tag. Please update your tag variable"
              exit 1
            fi
          }

      - name: Push the new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ inputs.VERSION }}
          git push origin ${{ inputs.VERSION }}