name: Tagging template

on:
  workflow_call:
    inputs:
      VERSION:
        description: "Application version"
        type: string
        required: true
        default: "1.0.0"

jobs:
  tag_control:
    if: github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_latest_tag
        run: |
          # Fetch tags and sort them in descending order by version
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          LATEST_SEMVER_TAG=$(git tag -l | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          echo "latest_tag=$LATEST_SEMVER_TAG" >> $GITHUB_ENV

      - name: Version check
        run: |
          # Convert VERSION_1 and VERSION_2 to positional variables
          NEW_TAG=${{ inputs.VERSION }}
          LAST_TAG=${{ env.latest_tag || 'v0.0.0' }}

          # Extract the 'v' prefix
          NEW_TAG_NO_V="${NEW_TAG#v}"
          LAST_TAG_NO_V="${LAST_TAG#v}"

          # Validate if valid SemVer format
          if ! [[ "$NEW_TAG_NO_V" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: New tag $NEW_TAG is not a valid SemVer!"
            exit 1
          fi

          # Compare versions
          if [[ "$(echo -e "$NEW_TAG_NO_V\n$LAST_TAG_NO_V" | sort -V | head -n1)" != "$LAST_TAG_NO_V" || "$NEW_TAG_NO_V" == "$LAST_TAG_NO_V" ]]; then
            echo "Error: New tag $NEW_TAG is not higher than last tag $LAST_TAG!"
            exit 1
          fi

          echo "New tag $NEW_TAG is valid, higher than, and not equal to last tag $LAST_TAG."

  push_tag:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Push the new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ inputs.VERSION }}
          git push origin ${{ inputs.VERSION }}